train_data_file = ./data/deep/learn.25M.dim.fvecs
index_data_file = ./data/deep/base.1B.dim.fvecs
model_file = ./output/deep_model
index_dir = ./output/deep_index
index_file_num = 32
dim = 96
kmeans_epoch = 20
kmeans_sample_rete = 1
batch_size = 128
kmeans_centers_select_type = 3
first_cluster_num = 25000
second_cluster_num = 2000
hierachical_cluster_epoch = 3
read_file_batch_size = 128
build_index_search_first_center_num = 200
search_first_center_num = 200
search_second_center_num = 4900
is_disk = 1
search_neighbors = 2000000
search_block_num = 4900
search_top_cut = 7000
hs_mode = 0
thread_num = 32
read_index_file_thread_num = 1
build_index_num = -1
train_data_num = -1
use_uint8_data = 0
io_thread_num = 0
is_async_read = 0 #未完成
use_cache = 0
cache_capacity = 0
cache_segment = 0
dynamic_prune_switch = 1
dynamic_prune_a = 425.2
dynamic_prune_b = 183.2
dynamic_prune_c = -1.3
build_search_topk = 1
build_search_first_center_id_diff = 10